executors:
  nbcollection-builder:
    docker:
    - image: continuumio/miniconda3:latest
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Ifu Cube Continuum Fit:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names IFU_cube_continuum_fit
        name: Build Jdat Notebooks-Ifu Cube Continuum Fit notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Specviz Notebookgui Interaction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names specviz_notebookGUI_interaction
        name: Build Jdat Notebooks-Specviz Notebookgui Interaction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Publish Website:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
        no_output_timeout: 120m
    - run:
        command: nbcollection-ci merge-artifacts -c jdat_notebooks -o $CIRCLE_PROJECT_USERNAME
          -r $CIRCLE_PROJECT_REPONAME
        name: Publish Website
        no_output_timeout: 120m
    - add_ssh_keys
    - run:
        command: nbcollection-ci site-deployment -r origin -b gh-pages
        name: Deploy Website
        no_output_timeout: 120m
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Jdat Notebooks-Ifu Cube Continuum Fit
    - Jdat Notebooks-Specviz Notebookgui Interaction
    - Pull Request
    #- Publish Website:
    #    requires:
    #    - Jdat Notebooks-Ifu Cube Continuum Fit
    #    - Jdat Notebooks-Specviz Notebookgui Interaction
  version: '2.1'
